### PR TITLE
add new Property for normalize filename with str::slug() funcation

### PR DESCRIPTION
**Pull request by vahidalvandi**
**plz change package name in composer.json**
i added filenameSlugable in config and in FileManager.php and events FilesUploaded , FilesUploading use a simple function for slug file name . remove space and Unauthorized character this very important in correctly show image and use in ftp

### CODE REVIEW

**Comment by alexusmai** [comment]
Hi, please give me files which incorrectly showing

**Comment by vahidalvandi** [comment]
i changed composer.json name to **vahid alvandi** change it to **alexusmai/laravel-file-manager**

**Comment by alexusmai** [comment]
> remove space and Unauthorized character this very important in correctly show image and use in ftp

**Comment by vahidalvandi** [comment]
after very tray best wey usr Slug

**Pull request closed without merging**
